events {
    worker_connections 1024;
}
http {
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;
        root /usr/share/nginx/html;
        index index.html;

        add_header Set-Cookie "session=abc123; Path=/" always;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
